    ### USUARIOS ###

### Crear Usuario
POST http://localhost:3001/Usuarios/crear
### Obtener Usuarios
GET http://localhost:3001/Usuarios/obtenerTodos
### Obtener Usuarios por Email
GET http://localhost:3001/Usuarios/obtenerUsuario/luis@upchiapas.edu



    ### PUBLICACIONES ###

### Crear Publicacion
POST http://localhost:3001/Publicacion/crear
### Obtener Publicaciones
GET http://localhost:3001/Publicacion/obtenerTodos



    ### COMENTARIOS ###

### Crear Comentario
POST http://localhost:3001/Comentario/crear
### Obtener Publicaciones
GET http://localhost:3001/Comentario/obtenerTodos