### Obtener todos los productos
GET http://localhost:3000/productos/obtener

### Crear un producto
POST http://localhost:3000/productos/crear
Content-Type: application/json

{
    "cantidad_stock":15,
    "costo":200,
    "tipo":"dulces",
    "producto":{
        "nombre":"Dulces de propoleo",
        "marca":"Abejorro"
    }
}

### Producto por Id
GET http://localhost:3000/productos/obtener/6528c2a4841edb5523ff12bc
### Actualizar por Id
PATCH  http://localhost:3000/productos/actualizar/6528c3e493e57863ca801f4e
Content-Type: application/json

{
    "cantidad_stock":15,
    "costo":200,
    "tipo":"dulces",
    "producto":{
        "nombre":"Dulces de miel",
        "marca":"Abejorro"
    }
}
### Borrar por Id
DELETE  http://localhost:3000/productos/borrar/6528c3e493e57863ca801f4e






### crear Paciente
POST http://localhost:3000/paciente/crear
Content-Type: application/json

{
    "nombre":"David",
    "apellido":"Vazquez",
    "telefono":9618902353,
    "edad":19,
    "codigo_ajeno":123,
    "codigo_propio":456
}

### Obtener todos los pacientes
GET http://localhost:3000/paciente/obtener

### Paciente por Id
GET http://localhost:3000/paciente/obtener/652cae8cecc4ed19f3cb2612
### Actualizar Paciente por Id
PATCH  http://localhost:3000/paciente/actualizar/652999e78272c357efe7400b
Content-Type: application/json


{
    "nombre":"Luis",
    "apellido":"Vazquez",
    "telefono":9618902353,
    "edad":19,
    "codigo_ajeno":123,
    "codigo_propio":456
}

### Borrar por Id
DELETE  http://localhost:3000/paciente/borrar/652999e78272c357efe7400b

### Borrar por Todos los clientes
DELETE  http://localhost:3000/paciente/borrartodo

## Crear un usuario
POST http://localhost:3000/usuarios/crear
Content-Type: application/json

{
    "Nombre_usuario":"Admin",
    "Contraseña":"1234",
    "Persona":{
        "Nombre":"Luis David",
        "Apellido":"Vazquez",
        "Puesto":"Administrador"
    }
}

### Obtener todos los usuarios
GET http://localhost:3000/usuarios/obtener

### Producto por Id
GET http://localhost:3000/usuarios/obtener/65299b7060013362e375d269

### Actualizar por Id
PATCH  http://localhost:3000/usuarios/actualizar/65299b7060013362e375d269
Content-Type: application/json

{
    "Nombre_usuario":"Admin",
    "Contraseña":"1234",
    "Persona":{
        "Nombre":"Rodrigo Eliseo",
        "Apellido":"García",
        "Puesto":"Gerente"
    }
}

### Borrar por Id
DELETE  http://localhost:3000/usuarios/borrar/65299dc960013362e375d27a
###//PETICIONES DE LA TAREA //###
### Crear usuario red social
POST  http://localhost:3000/users/crear
Content-Type: application/json

{
    "email":"Borrado@outlook.es",
    "contraseña":"eldeividjajaasies"
}

### Crear publicacion red social
POST  http://localhost:3000/publicacion/crear
Content-Type: application/json

{
    "titulo":"Ya tengo chamba",
    "contenido":"quiero renunciar",
    "etiqueta":"Trabajo",
    "usuario":"65386c75ba917dc958e921a7"
}

### Crear publicaciones red social
POST  http://localhost:3000/publicacion/crearMuchos
Content-Type: application/json

[
  {
    "titulo": "Hola mundo",
    "contenido": "Este es mi primer programa",
    "etiqueta":"Social",
    "fechaCreación": "2023-10-22T00:00:00.000Z",
    "usuario": "65386c75ba917dc958e921a7"
  },
  {
    "titulo": "Viaje por el mundo",
    "contenido": "Me voy a vivir a suchiapa",
    "etiqueta":"Noticias",
    "fechaCreación": "2023-10-22T00:00:00.000Z",
    "usuario": "65386c75ba917dc958e921a7"
  }
]
### Crear comentario
POST http://localhost:3000/comentario/crear
Content-Type: application/json

{
    "contenido":"Por ahi roban, ten cuidado",
    "usuario":"65386da8ba917dc958e921ab",
    "publicacion":"6539e92edca6874ca39f7a8f"
}

### Crear varios comentarios
POST http://localhost:3000/comentario/crearMuchos
Content-Type: application/json
[
{
    "contenido":"Por ahi roban, ten cuidado",
    "usuario":"65386da8ba917dc958e921ab",
    "publicacion":"6539e92edca6874ca39f7a8f"
},
{
    "contenido":"Por ahi roban, ten cuidado",
    "usuario":"65386da8ba917dc958e921ab",
    "publicacion":"6539e92edca6874ca39f7a8f"
},
]
### Actulizar comentario por id
PATCH http://localhost:3000/comentario/actualizar/6539eadd87cf8801fdec3228
Content-Type: application/json

{
    "contenido" : "Saluditos a todos, pasenla bonito pero bonito bonito"
}

### Actulizar publicacion por id
PATCH http://localhost:3000/publicacion/actualizar/6539e92edca6874ca39f7a8e
Content-Type: application/json

{
    "titulo" : "Adios mundo",
    "contenido" : "Mi ultimo programa, me doy de baja"
}

### 1 Obtener usuario red social por email
GET http://localhost:3000/users/buscar/ryazru1993@gmail.com

### 2A Obtener publicaciones por id del usuario
GET http://localhost:3000/publicacion/publicacionesxusuario/65386c75ba917dc958e921a7

### 2B Obtener todas las publicaciones con su usuario (quien las hizo)
GET http://localhost:3000/publicacion/publicacionesconusuario
### 3 Obtener todas las publicaciones con comentarios
GET http://localhost:3000/publicacion/publicacioncomentarios

### 4 Obtener todas las publicaciones con su usuario, clasificadas por etiquetas
GET http://localhost:3000/publicacion/publicacionesconusuario/Trabajo


### Borrar por usuario Id
DELETE  http://localhost:3000/users/borrar/653af3c824d392a2c6e375bf

### Borrar publicacion por fechaCreacion
DELETE  http://localhost:3000/publicacion/borrar/2023-10-22T00:00:00.000Z

###EXTRAS
### obtener usuarios red social
GET http://localhost:3000/users/obtener

### Obtener usuario red social id
GET http://localhost:3000/users/obtener/6539d8ab817e6f157672af0e

### obtener todas publicaciones red social
GET http://localhost:3000/publicacion/obtener

### Obtener todos los comentarios 
GET http://localhost:3000/comentario/obtener





